### ISSUE TITLE
ads4U not appearing in all templates

### ISSUE THREAD

**Issue by oleteacher** [dignajar/bludit-plugins#139]
Hi.

Could you give me some tips on getting ads4u working with template like "Clean Blog"?

Plugin works fine in "Kernel Panic" theme so hoping for tips:)

Thank you!

**Comment by dignajar** [comment]
Hi, maybe the best way is to contact the developer of ADS4u.
This repository is not updated anymore, check the page https://plugins.bludit.com with the new version and new plugins.

**Comment by oleteacher** [comment]
Yes, I contacted the author on their GitHub page and got this response:

"Hi!This question should be asked to themes authors because plugin uses Bludit ‎ standard pages markup which seems not fully supported in all themes"

So I give up. Not that great of a plugin anyway:)

Thank you for response.
