### ISSUE TITLE
Error message: The JSON file with many plugins can not be found

### ISSUE THREAD

**Issue by ghost** [dignajar/bludit-plugins#31]
Hello Developers,

I discovered your CMS and already installed. However, right after installation numerous error messages were displayed to me. The json file of many plugins that I have here, can not be found.

I'm interested in, for example, the plugin "cookie consent" and others, and since there is no json file.

How can you solve the problem?

Looking forward to your help and thank you very much.

**Comment by Fred89** [comment]
Just let me update all plugins with Bludit 1.0.x.
Is done now!
