### ISSUE TITLE
sitemaps

### ISSUE THREAD

**Issue by duke-chai** [dignajar/bludit-plugins#32]
sitemaps not work?

**Comment by AbrahamAriel** [comment]
It works fine on my end. http://www.iamnobuna.ga/sitemap.xml

Have you enabled the plugin?

**Comment by gaurav-chandra** [comment]
The sitemaps are working. But there is a problem with the <lastmod> in case of pages.

The page dates is stored as `2016-01-07 10:40` and posts date is stored as `2016-01-07 10:40:00`, the date conversion in plugin file is returning false in case of pages and lastmod element is empty. As a result, google web master tools is showing an error.

**Comment by AbrahamAriel** [comment]
I noticed that those only occurred with old pages that were created prior to version 1.0.

**Comment by duke-chai** [comment]
Sitemap can not work in  version 0.72 .  Work in  version1.0.1 . Thanks.

**Comment by dignajar** [comment]
There is a bug on the updated manager on page's dates, to workarround you can edit the page and save it, this fix the page's date.

**Comment by gaurav-chandra** [comment]
It does not work for me. Re saving page does not change the date. I had to change the dates manually.

**Comment by AbrahamAriel** [comment]
Same here. I thought of that when I updated to 1.0 yesterday, but maybe we
really need to modify the contents instead of just saving it again.

I haven't update to 1.0.1 so I can't say anything for sure yet. I'll do
that when I can.

**Comment by dignajar** [comment]
Could you try updating this file, https://github.com/dignajar/bludit/blob/master/bl-kernel/admin/controllers/dashboard.php

Then go to the admin panel and add this parameter on the uri.

www.domain.com/admin/?update=true

**Comment by Krakengr** [comment]
Sitemap not working for me too (1.0.1). I changed it my self to work properly (google gives an error even in home url).
http://homebrewgr.info/en/sitemap.xml

**Comment by Krakengr** [comment]
Also the sitemap indexes and the draft posts, not only the published.

**Comment by dignajar** [comment]
Hi @Krakengr , what was your changes, the date format ?

**Comment by AbrahamAriel** [comment]
@Krakengr It doesn't index draft posts on mine. Are you sure those posts are drafts?

@dignajar I tried your updated dashboard.php. That parameter returned this:
`Fatal error: Call to undefined method dbPages::setPostDb() in /home1/nozomi/public_html/bl-kernel/admin/controllers/dashboard.php on line 31`

**Comment by dignajar** [comment]
@acrox999 sorry, my bad, I don't update the files.

https://github.com/dignajar/bludit/blob/master/bl-kernel/admin/controllers/dashboard.php

And this file too:
https://github.com/dignajar/bludit/blob/master/bl-kernel/dbpages.class.php

**Comment by dignajar** [comment]
FIxed, the posts and pages not published will not showed on sitemap.

**Comment by Krakengr** [comment]
@dignajar
I changed the code a bit, because the 
`$date = Date::format($db['date'], DB_DATE_FORMAT, SITEMAP_DATE_FORMAT)` 
seems not working properly

**Comment by dignajar** [comment]
@Krakengr yes I know, because the DB_DATE_FORMAT on pages are not equals in format.

You need to update this files 
https://github.com/dignajar/bludit/blob/master/bl-kernel/admin/controllers/dashboard.php
https://github.com/dignajar/bludit/blob/master/bl-kernel/dbpages.class.php

Login to dashboard, then go to www.domain.com/admin/?update=true

With this changes, the pages will be have a correct date format.

**Comment by dignajar** [comment]
This bug is fixed on the latest version of Bludit v1.1. Feel free to open a new issues.
