### ISSUE TITLE
Updated and have image path issues

### ISSUE THREAD

**Issue by 2braincells2go** [dignajar/bludit-plugins#34]
I am running http://www.bludit.com/bludit_latest.zip and updated the ckeditor to latest and seems there is a path issue.

Can no longer get images to appear when inserting via filemanger. inserted as:

http://example.com/bludit/bl-bl-content/uploads/test.png

Images are uploaded correctly to "bludit/bl-content/uploads" but when inserting into post/pages with filemanager, the path is "bludit/bl-bl-content/uploads/"

**Comment by AbrahamAriel** [comment]
Same here. I wonder if there's an error somewhere during submission with the CKeditor.

**Comment by AbrahamAriel** [comment]
Hi, I've made a fix. It worked for me. I hope it works for you too. Just change `''upload_dir' => 'bl-content/uploads/',` to `'upload_dir' => 'content/uploads/',` at bl-plugins/ckeditor/libs/filemanager/config/config.php.

#36

**Comment by 2braincells2go** [comment]
Thanks @acrox999, that seem to fix things. I had tried a few changes in the config.php but changed all 3 related paths. Just changing the upload_dir did the trick!

**Comment by Fred89** [comment]
Ckeditor is updated to Bludit 1.0.1, fixed base path for filemanager.
