### ISSUE TITLE
Plugin Cookie-Consent doesn´t work right after update / clean Installation 

### ISSUE THREAD

**Issue by netbuk** [dignajar/bludit-plugins#35]
Hello there,
after updating to v1.0.1 Bludit and the plug-in cookie consent to v1.0.1, the plug-in doesn´t work anymore. The same problem also exists for a clean installation.
In Apache2 error.log there is this line: "[: error] [pid xxxx] [client xxxx] build page | when you try to build the page from the file with major errors: plugins / cookie consent / configurator themes / dark floating.css, referer: http: // xxxxx ".
Where is the Problem?
In the previous version yet everything worked.

**Comment by dignajar** [comment]
Hi,
after upgrade Bludit, you make the upgrade of the plugin ?

**Comment by dignajar** [comment]
Here is the thread of the plugin, http://forum.bludit.com/viewtopic.php?f=14&t=62

**Comment by Fred89** [comment]
Plugin update to Bludit 1.0.1

**Comment by netbuk** [comment]
After the new plug-in update everything works fine. thx
