### ISSUE TITLE
Minor: Contact plugin (string untranslated/untranslateable)

### ISSUE THREAD

**Issue by CryssDOTnet** [dignajar/bludit-plugins#44]
String "Please enter an email address." is nowhere to be found in the language file or in other code.
I am using Bludit 1.0.1 (German) with the latest Contact Plugin. Any hints?

**Comment by Fred89** [comment]
Hi,
The correct string is "Please enter a valid email address" ;)

**Comment by CryssDOTnet** [comment]
I can't take a screenshot  right now, but it definitely says "Please enter an email address." Maybe it is in the Bludit code, I could'nt find it with the search function. Install the plugin and put some strings in the mail part of the form. Then move the mouse away and back again. Now you should see the message.

**Comment by CryssDOTnet** [comment]
The string you mentioned is given back when you click the send button without entering a valid email.

**Comment by Fred89** [comment]
Sorry i don't reproduct this error.
And i don't found the string "Please enter an email address." in all Bludit code....
Do you have other plugins installed?
Please desactivate all plugins (execpt Bludit defaut plugin) and check one by one.

**Comment by dignajar** [comment]
I close the issues, it has more than 20 days without update. Feel free to open a new issues.
