### ISSUE TITLE
 Missing the metadata file for two plugins

### ISSUE THREAD

**Issue by DrXala** [dignajar/bludit-plugins#65]
For `coverimage` :

```
Warning: file_get_contents(/data1/www/www.clamifa.net/bludit/bl-plugins/coverimage/metadata.json): failed to open stream: Aucun fichier ou dossier de ce type in /data1/www/www.clamifa.net/bludit/bl-kernel/abstract/plugin.class.php on line 47
```

And `gitter` :

```
Warning: file_get_contents(/data1/www/www.clamifa.net/bludit/bl-plugins/gitter/metadata.json): failed to open stream: Aucun fichier ou dossier de ce type in /data1/www/www.clamifa.net/bludit/bl-kernel/abstract/plugin.class.php on line 47
```

**Comment by dignajar** [comment]
Hi, coverimage is deprecated, I wil check Gitter.

**Comment by dignajar** [comment]
Anyway, if the plugin has not the metada.json, they will not appear on the webpage.

**Comment by DrXala** [comment]
It's not a problem for me, I have fix it with a copy of metadata file from other plugin.
I do not agree, these messages appear in webpage head (blog or admin panel).

I created this issue for your information. If you want, you can close it ;)
