### ISSUE TITLE
Gitter plugin outdated

### ISSUE THREAD

**Issue by alexandreteles** [dignajar/bludit-plugins#78]
The sidecar lib loaded using Gitter plugin is outdated (the plugin uses 1.1.3, latest is 1.2.4). Someone that uses Gitter can test if the latest version can be a drop in replacement for the version included with this plugin or if we need to work some code to update it?

**Comment by Fred89** [comment]
You have the Shortcode API with Gitter Shortcode exemple: {Gitter room='dignajar/bludit'}
This plugin does not really need to be...
